server:
  port: ":8080"
  mode: debug
  base_path: "/datax"

database:
  host: 127.0.0.1
  port: 13306
  username: root
  password: 123456
  dbname: datax_admin
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

jwt:
  secret: your-secret-key
  expire: 86400  # 24 hours

log:
  level: debug
  filename: logs/datax-admin.log
  max_size: 100
  max_age: 30
  max_backups: 10
