server:
  port: ":28080"
  mode: debug
  base_path: "/"

db:
  host: 192.168.228.1
  port: 13306
  username: root
  password: 123456
  dbname: datax_admin
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
  log_mode: info
  charset: utf8mb4

jwt:
  secret: your-secret-key
  expire: 86400  # 24 hours

datax:
  home: "/app"  # DataX 安装目录
  bin: "/app/bin/datax"  # DataX 可执行文件路径

logger:
  log_path: "logs"  # 日志文件路径
  max_size: 100     # 单个日志文件最大大小（MB）
  max_backups: 7    # 最大保留的旧日志文件数
  max_age: 30       # 日志文件保留的最大天数
  compress: true    # 是否压缩旧日志文件

